    <h1 id="firstHeading" class="firstHeading">try-block</h1>            <p>Associates one or more exception handlers (catch-clauses) with a compound statement.</p>
<h3 id="Syntax"> Syntax</h3> <table class="t-sdsc-begin">  <tr class="t-sdsc"> <td class="t-sdsc-nopad"> <code>try</code> <span class="t-spar">compound-statement</span> <span class="t-spar">handler-sequence</span> </td> <td class="t-sdsc-nopad"> </td> <td class="t-sdsc-nopad"> </td>
</tr> 
</table> <p>where <span class="t-spar">handler-sequence</span> is a sequence of one or more <span class="t-spar">handler</span>s, which have the following syntax:</p>
<table class="t-sdsc-begin">  <tr class="t-sdsc"> <td> <code>catch</code> <code>(</code> <span class="t-spar">attr</span> ﻿<span class="t-mark">(optional)</span> <span class="t-spar">type-specifier-seq</span> <span class="t-spar">declarator</span> <code>)</code> <span class="t-spar">compound-statement</span> </td> <td> (1) </td> <td class="t-sdsc-nopad"> </td>
</tr>  <tr class="t-sdsc"> <td> <code>catch</code> <code>(</code> <span class="t-spar">attr</span> ﻿<span class="t-mark">(optional)</span> <span class="t-spar">type-specifier-seq</span> <span class="t-spar">abstract-declarator</span> ﻿<span class="t-mark">(optional)</span> <code>)</code> <span class="t-spar">compound-statement</span> </td> <td> (2) </td> <td class="t-sdsc-nopad"> </td>
</tr>  <tr class="t-sdsc"> <td> <code>catch</code> <code>(</code> <code>...</code> <code>)</code> <span class="t-spar">compound-statement</span> </td> <td> (3) </td> <td class="t-sdsc-nopad"> </td>
</tr> 
</table> <table class="t-par-begin"> <tr class="t-par"> <td> <span class="t-spar">compound-statement</span> </td> <td> - </td> <td> brace-enclosed <a href="statements.html#Compound_statements" title="cpp/language/statements">sequence of statements</a> </td>
</tr> <tr class="t-par"> <td> <span class="t-spar">attr</span> </td> <td> - </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> any number of <a href="attributes.html" title="cpp/language/attributes">attributes</a>, applies to the formal parameter </td>
</tr> <tr class="t-par"> <td> <span class="t-spar">type-specifier-seq</span> </td> <td> - </td> <td> part of a formal parameter declaration, same as in a <a href="function.html" title="cpp/language/function">function</a> parameter list </td>
</tr> <tr class="t-par"> <td> <span class="t-spar">declarator</span> </td> <td> - </td> <td> part of a formal parameter declaration, same as in a <a href="function.html" title="cpp/language/function">function</a> parameter list </td>
</tr> <tr class="t-par"> <td> <span class="t-spar">abstract-declarator</span> </td> <td> - </td> <td> part of an unnamed formal parameter declaration, same as in <a href="function.html" title="cpp/language/function">function</a> parameter list </td>
</tr>
</table> <div class="t-li1">
<span class="t-li">1)</span> Catch-clause that declares a named formal parameter <div class="cpp source-cpp"><pre data-language="cpp">try { /* */ } catch (const std::exception&amp; e) { /* */ }</pre></div>
</div> <div class="t-li1">
<span class="t-li">2)</span> Catch-clause that declares an unnamed parameter <div class="cpp source-cpp"><pre data-language="cpp">try { /* */ } catch (const std::exception&amp;) { /* */ }</pre></div>
</div> <div class="t-li1">
<span class="t-li">3)</span> Catch-all handler, which is activated for any exception <div class="cpp source-cpp"><pre data-language="cpp">try { /* */ } catch (...) { /* */ }</pre></div>
</div> <h3 id="Explanation"> Explanation</h3> See <a href="throw.html" title="cpp/language/throw">throw exceptions</a> for more information about throw-expressions  <p>A try-block is a <a href="statements.html" title="cpp/language/statements">statement</a>, and as such, can appear anywhere a statement can appear (that is, as one of the statements in a compound statement, including the function body compound statement). See <a href="function-try-block.html" title="cpp/language/function-try-block">function-try-block</a> for the try blocks around function bodies. The following description applies to both try-blocks and <a href="function-try-block.html" title="cpp/language/function-try-block">function-try-blocks</a>.</p>
<p>The formal parameter of the catch clause (<span class="t-spar">type-specifier-seq</span> and <span class="t-spar">declarator</span> or <span class="t-spar">type-specifier-seq</span> and <span class="t-spar">abstract-declarator</span>) determines which types of exceptions cause this catch clause to be entered. It cannot be an <a href="incomplete_type.html" title="cpp/language/incomplete type" class="mw-redirect">incomplete type</a>, <a href="abstract_class.html" title="cpp/language/abstract class">abstract class</a> type,<span class="t-rev-inl t-since-cxx11"><span> <a href="reference.html" title="cpp/language/reference">rvalue reference</a> type,</span><span><span class="t-mark-rev t-since-cxx11">(since C++11)</span></span></span> or pointer to incomplete type (except that pointers to (possibly <a href="cv.html" title="cpp/language/cv">cv</a>-qualified) <code>void</code> are allowed). If the type of the formal parameter is array type or function type, it is treated as the corresponding pointer type (similar to a <a href="function.html" title="cpp/language/function">function declaration</a>).</p>
<p>When an exception is thrown by any statement in <span class="t-spar">compound-statement</span>, the <a href="throw.html#The_exception_object" title="cpp/language/throw">exception object</a> of type <code>E</code> is matched against the types of the formal parameters <code>T</code> of each catch-clause in <span class="t-spar">handler-seq</span>, in the order in which the catch clauses are listed. The exception is a match if any of the following is true:</p>
<ul>
<li> <code>E</code> and <code>T</code> are the same type (ignoring top-level cv-qualifiers on <code>T</code>) </li>
<li> <code>T</code> is an lvalue-reference to (possibly cv-qualified) <code>E</code> </li>
<li> <code>T</code> is an unambiguous public base class of <code>E</code> </li>
<li> <code>T</code> is a reference to an unambiguous public base class of <code>E</code> </li>
<li> <code>T</code> is (possibly cv-qualified) <code>U</code> or <code>const U&amp;</code>, and <code>U</code> is a pointer or pointer to member type, and <code>E</code> is also a pointer or pointer to member type that is implicitly convertible to <code>U</code> by one or more of </li>
<ul>
<li> a standard <a href="implicit_conversion.html#Pointer_conversions" title="cpp/language/implicit conversion">pointer conversion</a> other than one to a private, protected, or ambiguous base class </li>
<li> a <a href="implicit_conversion.html#Qualification_conversions" title="cpp/language/implicit conversion">qualification conversion</a> </li>
</ul>
</ul>  <table class="t-rev-begin"> <tr class="t-rev t-since-cxx17">
<td> <ul><li> a <a href="implicit_conversion.html#Function_pointer_conversions" title="cpp/language/implicit conversion">function pointer conversion</a> </li></ul> </td> <td><span class="t-mark-rev t-since-cxx17">(since C++17)</span></td>
</tr> </table> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <ul><li> <code>T</code> is (possibly cv-qualified) <code>U</code> or <code>const U&amp;</code>, where <code>U</code> is a pointer or a pointer to member type, and <code>E</code> is <code><a href="../types/nullptr_t.html" title="cpp/types/nullptr t">std::nullptr_t</a></code>. </li></ul> </td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <div class="cpp source-cpp"><pre data-language="cpp">try
{
    f();
}
catch (const std::overflow_error&amp; e)
{} // this executes if f() throws std::overflow_error (same type rule)
catch (const std::runtime_error&amp; e)
{} // this executes if f() throws std::underflow_error (base class rule)
catch (const std::exception&amp; e)
{} // this executes if f() throws std::logic_error (base class rule)
catch (...)
{} // this executes if f() throws std::string or int or any other unrelated type</pre></div> <p>The catch-all clause <code>catch (...)</code> matches exceptions of any type. If present, it has to be the last catch clause in the <span class="t-spar">handler-seq</span>. Catch-all block may be used to ensure that no uncaught exceptions can possibly escape from a function that offers <a href="exceptions.html" title="cpp/language/exceptions">nothrow exception guarantee</a>.</p>
<p>If no matches are found after all catch-clauses were examined, the exception propagation continues to the containing try-block, as described in <a href="throw.html" title="cpp/language/throw">throw-expression</a>. If there are no containing try-blocks left, <code><a href="../error/terminate.html" title="cpp/error/terminate">std::terminate</a></code> is executed (in this case, it is implementation-defined whether any stack unwinding occurs at all: throwing an uncaught exception is permitted to terminate the program without invoking any destructors).</p>
<p>When entering a catch clause, if its formal parameter is a base class of the exception type, it is <a href="copy_initialization.html" title="cpp/language/copy initialization">copy-initialized</a> from the base class subobject of the exception object. Otherwise, it is copy-initialized from the exception object (this copy is subject to <a href="copy_elision.html" title="cpp/language/copy elision">copy elision</a>).</p>
<div class="cpp source-cpp"><pre data-language="cpp">try
{
    std::string("abc").substr(10); // throws std::length_error
}
// catch (std::exception e) // copy-initialization from the std::exception base
// {
//     std::cout &lt;&lt; e.what(); // information from length_error is lost
// }
catch (const std::exception&amp; e) // reference to the base of a polymorphic object
{
    std::cout &lt;&lt; e.what(); // information from length_error printed
}</pre></div> <p>If the parameter of the catch-clause is a reference type, any changes made to it are reflected in the exception object, and can be observed by another handler if the exception is rethrown with <code>throw;</code>. If the parameter is not a reference, any changes made to it are local and its lifetime ends when the handler exits.</p>
<table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <p>Within a catch-clause, <code><a href="../error/current_exception.html" title="cpp/error/current exception">std::current_exception</a></code> can be used to capture the exception in an <code><a href="../error/exception_ptr.html" title="cpp/error/exception ptr">std::exception_ptr</a></code>, and <code><a href="../error/throw_with_nested.html" title="cpp/error/throw with nested">std::throw_with_nested</a></code> may be used to build nested exceptions.</p>
</td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <p>A <a href="goto.html" title="cpp/language/goto">goto</a> or <a href="switch.html" title="cpp/language/switch">switch</a> statement shall not be used to transfer control into a try block or into a handler.</p>
<p>Other than by throwing or rethrowing the exception, the catch-clause after a regular try block (not <a href="function-try-block.html" title="cpp/language/function-try-block">function-try-block</a>) may be exited with a <a href="return.html" title="cpp/language/return">return</a>, <a href="continue.html" title="cpp/language/continue">continue</a>, <a href="break.html" title="cpp/language/break">break</a>, <a href="goto.html" title="cpp/language/goto">goto</a>, or by reaching the end of its <span class="t-spar">compound-statement</span>. In any case, this destroys the exception object (unless an instance of <code><a href="../error/exception_ptr.html" title="cpp/error/exception ptr">std::exception_ptr</a></code> exists that refers to it).</p>
<h3 id="Notes"> Notes</h3> <p>The throw-expression <code><span class="kw1">throw</span> <a href="http://en.cppreference.com/w/cpp/types/NULL"><span class="kw110">NULL</span></a><span class="sy4">;</span></code> is not guaranteed to be matched by a pointer catch clause, because the exception object type may be <code>int</code>, but <code>throw nullptr;</code> is assuredly matched by any pointer or pointer-to-member catch clause.</p>
<p>If a catch-clause for a derived class is placed after the catch-clause for a base class, the derived catch-clause will never be executed:</p>
<div class="cpp source-cpp"><pre data-language="cpp">try
{
    f();
}
catch (const std::exception&amp; e)
{} // will be executed if f() throws std::runtime_error
catch (const std::runtime_error&amp; e)
{} // dead code!</pre></div> <p>If <a href="goto.html" title="cpp/language/goto">goto</a> is used to exit a try-block and if any of the destructors of block-scoped automatic variables that are executed by the <code>goto</code> throw exceptions, those exceptions are caught by the try blocks in which the variables are defined:</p>
<div class="cpp source-cpp"><pre data-language="cpp">label:
    try
    {
        T1 t1;
        try
        {
            T2 t2;
            if (condition)
                goto label; // destroys t2, then destroys t1, then jumps to label
        }
        catch (...) {} // catches the exception from the destructor of t2
    }
    catch (...) {}     // catches the exception from the destructor of t1</pre></div> <p>Many implementations overly extend the resolution of <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/388.html">CWG388</a> to handlers of reference to non-const pointer types:</p>
<div class="cpp source-cpp"><pre data-language="cpp">int i;
try
{
    try
    {
        throw static_cast&lt;float*&gt;(nullptr);
    }
    catch (void*&amp; pv)
    {
        pv = &amp;i;
        throw;
    }
}
catch (const float* pf)
{
    assert(pf == nullptr); // should pass, but fails on MSVC and Clang
}</pre></div> <h3 id="Keywords"> Keywords</h3> <p><a href="../keyword/try.html" title="cpp/keyword/try"><code>try</code></a>, <a href="../keyword/catch.html" title="cpp/keyword/catch"><code>catch</code></a>, <a href="../keyword/throw.html" title="cpp/keyword/throw"><code>throw</code></a></p>
<h3 id="Example"> Example</h3> <div class="t-example">
<p>The following example demonstrates several usage cases of the <code>try-catch</code> block</p>
<div class="cpp source-cpp"><pre data-language="cpp">#include &lt;iostream&gt;
#include &lt;vector&gt;
 
int main()
{
    try
    {
        std::cout &lt;&lt; "Throwing an integer exception...\n";
        throw 42;
    }
    catch (int i)
    {
        std::cout &lt;&lt; " the integer exception was caught, with value: " &lt;&lt; i &lt;&lt; '\n';
    }
 
    try
    {
        std::cout &lt;&lt; "Creating a vector of size 5... \n";
        std::vector&lt;int&gt; v(5);
        std::cout &lt;&lt; "Accessing the 11th element of the vector...\n";
        std::cout &lt;&lt; v.at(10); // vector::at() throws std::out_of_range
    }
    catch (const std::exception&amp; e) // caught by reference to base
    {
        std::cout &lt;&lt; " a standard exception was caught, with message: '"
                  &lt;&lt; e.what() &lt;&lt; "'\n";
    }
}</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">Throwing an integer exception...
 the integer exception was caught, with value: 42
Creating a vector of size 5...
Accessing the 11th element of the vector...
 a standard exception was caught, with message: 'out_of_range'</pre></div> </div> <h3 id="Defect_reports"> Defect reports</h3> <p>The following behavior-changing defect reports were applied retroactively to previously published C++ standards.</p>
<table class="dsctable"> <tr> <th>DR </th> <th>Applied to </th> <th>Behavior as published </th> <th>Correct behavior </th>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/98.html">CWG 98</a> </td> <td>C++98 </td> <td>a switch statement can transfer control<br>into a try block or into a handler </td> <td>prohibited </td>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/210.html">CWG 210</a> </td> <td>C++98 </td> <td>the throw expression was matched against the catch clauses </td> <td>the exception object is matched<br>against the catch clauses </td>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/388.html">CWG 388</a> </td> <td>C++98 </td> <td>an exception of pointer or pointer to member type could not<br>be matched by a const reference to a different type </td> <td>made matchable when convertible </td>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/1166.html">CWG 1166</a> </td> <td>C++98 </td> <td>the behavior was unspecified when a catch clause whose<br>exception type is a reference to an abstract class type is matched </td> <td>abstract class types are not<br>allowed for catch clauses </td>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/1769.html">CWG 1769</a> </td> <td>C++98 </td> <td>when the type of the exception declared in the catch-clause is a<br>base of the type of the exception object, a converting constructor<br>might be used for the initialization of the catch-clause parameter </td> <td>the parameter is copy-initialized<br>from the corresponding base class<br>subobject of the exception object </td>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/2093.html">CWG 2093</a> </td> <td>C++98 </td> <td>an exception object of pointer to object type could not match a<br>handler of pointer to object type through qualification conversion </td> <td>allowed </td>
</tr>
</table>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/language/try_catch" class="_attribution-link">https://en.cppreference.com/w/cpp/language/try_catch</a>
  </p>
</div>
