<h1 id="class-Timeout::ExitException" class="class"> class Timeout::ExitException </h1>
<dl class="meta">
<dt>Parent:</dt>
<dd class="meta-parent"><a href="../exception.html">Exception</a></dd>
</dl> <section class="description"> <p>Internal error raised to when a timeout is triggered.</p> </section> <section id="5Buntitled-5D" class="documentation-section"> <section id="public-instance-5Buntitled-5D-method-details" class="method-section"> <header> <h3>Public Instance Methods</h3> </header> <div class="method-detail "> <div class="method-header"> <div class="method-heading" id="method-i-exception"> <span class="method-name">exception</span><span class="method-args">(*)</span> <a class="method-click-advice">Show source</a> </div> </div> <div class="method-description">
<div class="method-source-code" id="exception-source"> <pre class="ruby" data-language="ruby"># File lib/timeout.rb, line 30
def exception(*)
  self
end</pre> </div>  </div> </div> </section> </section><div class="_attribution">
  <p class="_attribution-p">
    Ruby Core &copy; 1993&ndash;2022 Yukihiro Matsumoto<br>Licensed under the Ruby License.<br>Ruby Standard Library &copy; contributors<br>Licensed under their own licenses.<br>
    
  </p>
</div>
