<h1>pandas.errors.OutOfBoundsDatetime</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.OutOfBoundsDatetime"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">OutOfBoundsDatetime</span></span>
</dt> <dd>
<p>Raised when the datetime is outside the range that can be represented.</p> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/1.5.0/reference/api/pandas.errors.OutOfBoundsDatetime.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/1.5.0/reference/api/pandas.errors.OutOfBoundsDatetime.html</a>
  </p>
</div>
