<header> <h1>assert.throws()</h1> <p class="post-meta">Categories: <a class="category" href="https://qunitjs.com/api/assert/">Assertions</a>.</p> </header> <p class="version-details"> version added: <a href="https://github.com/qunitjs/qunit/releases/tag/1.0.0">1.0.0</a><span class="sep">.</span></p> <h2 id="description" class="screen-reader-text h-api-desc">Description</h2> <p><code class="language-plaintext highlighter-rouge">throws( blockFn, message = "" )</code><br> <code class="language-plaintext highlighter-rouge">throws( blockFn, expectedMatcher, message = "" )</code></p> <p>Test if a callback throws an exception, and optionally compare the thrown error.</p> <table> <thead> <tr> <th>name</th> <th>description</th> </tr> </thead> <tbody> <tr> <td>
<code class="language-plaintext highlighter-rouge">blockFn</code> (function)</td> <td>Function to execute</td> </tr> <tr> <td><code class="language-plaintext highlighter-rouge">expectedMatcher</code></td> <td>Expected error matcher</td> </tr> <tr> <td>
<code class="language-plaintext highlighter-rouge">message</code> (string)</td> <td>Short description of the assertion</td> </tr> </tbody> </table> <p>When testing code that is expected to throw an exception based on a specific set of circumstances, use <code class="language-plaintext highlighter-rouge">assert.throws()</code> to catch the error object for testing and comparison.</p> <p>The <code class="language-plaintext highlighter-rouge">expectedMatcher</code> argument can be:</p> <ul> <li>An Error object.</li> <li>An Error constructor, evaluated as <code class="language-plaintext highlighter-rouge">errorValue instanceof expectedMatcher</code>.</li> <li>A RegExp that matches (or partially matches) the string representation.</li> <li>A callback Function that must return <code class="language-plaintext highlighter-rouge">true</code> to pass the assertion check.</li> </ul> <p class="note">In very few environments, like Closure Compiler, <code class="language-plaintext highlighter-rouge">throws</code> may cause an error. There you can use <code class="language-plaintext highlighter-rouge">assert.raises()</code>. It has the same signature and behaviour, just a different name.</p> <h2 id="changelog">Changelog</h2> <table> <tbody> <tr> <td><a href="https://github.com/qunitjs/qunit/releases/tag/2.12.0">QUnit 2.12</a></td> <td>Added support for arrow functions as <code class="language-plaintext highlighter-rouge">expectedMatcher</code> callback function.</td> </tr> <tr> <td><a href="https://github.com/qunitjs/qunit/releases/tag/v1.9.0">QUnit 1.9</a></td> <td>
<code class="language-plaintext highlighter-rouge">assert.raises()</code> was renamed to <code class="language-plaintext highlighter-rouge">assert.throws()</code>.<br>The <code class="language-plaintext highlighter-rouge">assert.raises()</code> method remains supported as an alias.</td> </tr> </tbody> </table> <h2 id="examples">Examples</h2> <div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight" data-language="javascript">QUnit.test('throws example', assert =&gt; {
  // simple check
  assert.throws(function () {
    throw new Error('boo');
  });

  // simple check
  assert.throws(
    function () {
      throw new Error('boo');
    },
    'optional description here'
  );

  // match pattern on actual error
  assert.throws(
    function () {
      throw new Error('some error');
    },
    /some error/,
    'optional description here'
  );

  // using a custom error constructor
  function CustomError (message) {
    this.message = message;
  }
  CustomError.prototype.toString = function () {
    return this.message;
  };

  // actual error is an instance of the expected constructor
  assert.throws(
    function () {
      throw new CustomError('some error');
    },
    CustomError
  );

  // actual error has strictly equal `constructor`, `name` and `message` properties
  // of the expected error object
  assert.throws(
    function () {
      throw new CustomError('some error');
    },
    new CustomError('some error')
  );

  // custom validation arrow function
  assert.throws(
    function () {
      throw new CustomError('some error');
    },
    (err) =&gt; err.toString() === 'some error'
  );

  // custom validation function
  assert.throws(
    function () {
      throw new CustomError('some error');
    },
    function (err) {
      return err.toString() === 'some error';
    }
  );
});
</pre></div></div><div class="_attribution">
  <p class="_attribution-p">
    &copy; OpenJS Foundation and contributors.<br>Licensed under the MIT license.<br>
    <a href="https://qunitjs.com/api/assert/throws" class="_attribution-link">https://qunitjs.com/api/assert/throws</a>
  </p>
</div>
