<h1 id="class-Ractor::RemoteError" class="class"> class Ractor::RemoteError </h1>
<dl class="meta">
<dt>Parent:</dt>
<dd class="meta-parent"><span>Ractor::Error</span></dd>
</dl> <section class="description"> <p>Raised on attempt to <a href="../ractor.html#method-i-take"><code>Ractor#take</code></a> if there was an uncaught exception in the <a href="../ractor.html"><code>Ractor</code></a>. Its <code>cause</code> will contain the original exception, and <code>ractor</code> is the original ractor it was raised in.</p> <pre class="ruby" data-language="ruby">r = Ractor.new { raise "Something weird happened" }

begin
  r.take
rescue =&gt; e
  p e             # =&gt; #&lt;Ractor::RemoteError: thrown by remote Ractor.&gt;
  p e.ractor == r # =&gt; true
  p e.cause       # =&gt; #&lt;RuntimeError: Something weird happened&gt;
end
</pre> </section> <section id="5Buntitled-5D" class="documentation-section"> <section class="attribute-method-details"> <header> <h3>Attributes</h3> </header> <div class="method-detail"> <div class="method-heading attribute-method-heading" id="attribute-i-ractor"> <span class="method-name">ractor</span><span class="attribute-access-type">[R]</span> </div>  </div> </section> </section><div class="_attribution">
  <p class="_attribution-p">
    Ruby Core &copy; 1993&ndash;2022 Yukihiro Matsumoto<br>Licensed under the Ruby License.<br>Ruby Standard Library &copy; contributors<br>Licensed under their own licenses.<br>
    
  </p>
</div>
