<h1 class="wp-block-wporg-code-reference-title">WP_Recovery_Mode::handle_error( <span class="arg-type">array</span> <span class="arg-name">$error</span> ): <span class="return-type">true|<a href="../wp_error.html" rel="class">WP_Error</a></span>
</h1> <section><p>Handles a fatal error occurring.</p> </section> <section><h2 id="description">Description</h2> <p>The calling API should immediately die() after calling this function.</p> </section> <section><h2 id="parameters">Parameters</h2> <dl>
<dt>
<code>$error</code><span class="type"><span class="array">array</span></span><span class="required">required</span>
</dt>
<dd><div class="desc"><span class="description">Error details from <code>error_get_last()</code>.</span></div></dd>
</dl></section> <section><h2 id="return">Return</h2> <span class="return-type">true|<a href="../wp_error.html" rel="class">WP_Error</a></span> True if the error was handled and headers have already been sent.<br> Or the request will exit to try and catch multiple errors at once.<br> <a href="../wp_error.html" rel="class">WP_Error</a> if an error occurred preventing it from being handled.</section> <section><h2 id="source">Source</h2> <pre class="wp-block-code" data-start="168" aria-label="Function source code" data-language="php"><code id="wporg-source-code" lang="php" class="language-php line-numbers">public function handle_error( array $error ) {

	$extension = $this-&gt;get_extension_for_error( $error );

	if ( ! $extension || $this-&gt;is_network_plugin( $extension ) ) {
		return new WP_Error( 'invalid_source', __( 'Error not caused by a plugin or theme.' ) );
	}

	if ( ! $this-&gt;is_active() ) {
		if ( ! is_protected_endpoint() ) {
			return new WP_Error( 'non_protected_endpoint', __( 'Error occurred on a non-protected endpoint.' ) );
		}

		if ( ! function_exists( 'wp_generate_password' ) ) {
			require_once ABSPATH . WPINC . '/pluggable.php';
		}

		return $this-&gt;email_service-&gt;maybe_send_recovery_mode_email( $this-&gt;get_email_rate_limit(), $error, $extension );
	}

	if ( ! $this-&gt;store_error( $error ) ) {
		return new WP_Error( 'storage_error', __( 'Failed to store the error.' ) );
	}

	if ( headers_sent() ) {
		return true;
	}

	$this-&gt;redirect_protected();
}
</code></pre>
<p class="wporg-dot-link-list"><a href="https://developer.wordpress.org/reference/files/wp-includes/class-wp-recovery-mode.php/">View all references</a> <a href="https://core.trac.wordpress.org/browser/tags/6.7/src/wp-includes/class-wp-recovery-mode.php#L168">View on Trac</a> <a href="https://github.com/WordPress/wordpress-develop/blob/6.7/src/wp-includes/class-wp-recovery-mode.php#L168-L197">View on GitHub</a></p></section>  <section><h2 id="changelog">Changelog</h2> <section style="margin-top:var(--wp--preset--spacing--20);"><figure class="wp-block-table "><table>
<thead><tr>
<th scope="col">Version</th>
<th scope="col">Description</th>
</tr></thead>
<tbody><tr class="">
<td><a href="https://developer.wordpress.org/reference/since/5.2.0/">5.2.0</a></td>
<td>Introduced.</td>
</tr></tbody>
</table></figure></section> </section><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2003&ndash;2024 WordPress Foundation<br>Licensed under the GNU GPLv2+ License.<br>
    <a href="https://developer.wordpress.org/reference/classes/wp_recovery_mode/handle_error" class="_attribution-link">https://developer.wordpress.org/reference/classes/wp_recovery_mode/handle_error</a>
  </p>
</div>
