<h1>   <span>Error and exception handling</span> </h1> <p>As with any other Elixir code, exceptions may happen during the LiveView life-cycle. In this section we will describe how LiveView reacts to errors at different stages.</p>
<h2 id="expected-scenarios" class="section-heading">  Expected scenarios </h2> <p>In this section, we will talk about error cases that you expect to happen within your application. For example, a user filling in a form with invalid data is expected. In a LiveView, we typically handle those cases by storing a change in the LiveView state, which causes the LiveView to be re-rendered with the error message.</p>
<p>We may also use <code class="inline">flash</code> messages for this. For example, imagine you have a page to manage all "Team members" in an organization. However, if there is only one member left in the organization, they should not be allowed to leave. You may want to handle this by using flash messages:</p>
<pre data-language="elixir">if MyApp.Org.leave(socket.assigns.current_org, member) do
  {:noreply, socket}
else
  {:noreply, put_flash(socket, :error, "last member cannot leave organization")}
end</pre>
<p>However, one may argue that, if the last member of an organization cannot leave it, it may be better to not even show the "Leave" button in the UI when the organization has only one member.</p>
<p>Given the button does not appear in the UI, triggering the "leave" when the organization has now only one member is an unexpected scenario. This means we can probably rewrite the code above to:</p>
<pre data-language="elixir">true = MyApp.Org.leave(socket.assigns.current_org, member)
{:noreply, socket}</pre>
<p>If <code class="inline">leave</code> returns false by any chance, it will just raise. Or you can even provide a <code class="inline">leave!</code> function that raises a specific exception:</p>
<pre data-language="elixir">MyApp.Org.leave!(socket.assigns.current_org, member)
{:noreply, socket}</pre>
<p>However, what will happen with a LiveView in case of exceptions? Let's talk about unexpected scenarios.</p>
<h2 id="unexpected-scenarios" class="section-heading">  Unexpected scenarios </h2> <p>Elixir developers tend to write assertive code. This means that, if we expect <code class="inline">leave</code> to always return true, we can explicitly match on its result, as we did above:</p>
<pre data-language="elixir">true = MyApp.Org.leave(socket.assigns.current_org, member)
{:noreply, socket}</pre>
<p>If <code class="inline">leave</code> fails and returns <code class="inline">false</code>, an exception is raised. It is common for Elixir developers to use exceptions for unexpected scenarios in their Phoenix applications.</p>
<p>For example, if you are building an application where a user may belong to one or more organizations, when accessing the organization page, you may want to check that the user has access to it like this:</p>
<pre data-language="elixir">organizations_query = Ecto.assoc(socket.assigns.current_user, :organizations)
Repo.get!(organizations_query, params["org_id"])</pre>
<p>The code above builds a query that returns all organizations that belongs to the current user and then validates that the given "org_id" belongs to the user. If there is no such "org_id" or if the user has no access to it, an <code class="inline">Ecto.NoResultsError</code> exception is raised.</p>
<p>During a regular controller request, this exception will be converted to a 404 exception and rendered as a custom error page, as <a href="../phoenix/custom_error_pages.html">detailed here</a>. To understand how a LiveView reacts to exceptions, we need to consider two scenarios: exceptions on mount and during any event.</p>
<h2 id="exceptions-on-mount" class="section-heading">  Exceptions on mount </h2> <p>Given the code on mount runs both on the initial disconnected render and the connected render, an exception on mount will trigger the following events:</p>
<p>Exceptions during disconnected render:</p>
<ol><li>An exception on mount is caught and converted to an exception page by Phoenix error views - pretty much like the way it works with controllers</li></ol>
<p>Exceptions during connected render:</p>
<ol>
<li>An exception on mount will crash the LiveView process - which will be logged</li>
<li>Once the client has noticed the crash during <code class="inline">mount</code>, it will fully reload the page</li>
<li>Reloading the page will start a disconnected render, that will cause <code class="inline">mount</code> to be invoked again and most likely raise the same exception. Except this time it will be caught and converted to an exception page by Phoenix error views</li>
</ol>
<p>In other words, LiveView will reload the page in case of errors, making it fail as if LiveView was not involved in the rendering in the first place.</p>
<h2 id="exceptions-on-events-handle_info-handle_event-etc" class="section-heading">  Exceptions on events (<code class="inline">handle_info</code>, <code class="inline">handle_event</code>, etc) </h2> <p>If the error happens during an event, the LiveView process will crash. The client will notice the error and remount the LiveView - without reloading the page. This is enough to update the page and show the user the latest information.</p>
<p>For example, let's say two users try to leave the organization at the same time. In this case, both of them see the "Leave" button, but our <code class="inline">leave</code> function call will succeed only for one of them:</p>
<pre data-language="elixir">true = MyApp.Org.leave(socket.assigns.current_org, member)
{:noreply, socket}</pre>
<p>When the exception raises, the client will remount the LiveView. Once you remount, your code will now notice that there is only one user in the organization and therefore no longer show the "Leave" button. In other words, by remounting, we often update the state of the page, allowing exceptions to be automatically handled.</p>
<p>Note that the choice between conditionally checking on the result of the <code class="inline">leave</code> function with an <code class="inline">if</code>, or simply asserting it returns <code class="inline">true</code>, is completely up to you. If the likelihood of everyone leaving the organization at the same time is low, then you may as well treat it as an unexpected scenario. Although other developers will be more comfortable by explicitly handling those cases. In both scenarios, LiveView has you covered.</p> <div class="bottom-actions"> <div class="bottom-actions-item"> <a href="assigns-eex.html" class="bottom-actions-button" rel="prev"> <span class="subheader"> ← Previous Page </span> <span class="title"> Assigns and HEEx templates </span> </a> </div> <div class="bottom-actions-item"> <a href="live-layouts.html" class="bottom-actions-button" rel="next"> <span class="subheader"> Next Page → </span> <span class="title"> Live layouts </span> </a> </div> </div><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2018 Chris McCord<br>Licensed under the MIT License.<br>
    <a href="https://hexdocs.pm/phoenix_live_view/error-handling.html" class="_attribution-link">https://hexdocs.pm/phoenix_live_view/error-handling.html</a>
  </p>
</div>
