<h1>pandas.errors.ChainedAssignmentError</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.ChainedAssignmentError"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">ChainedAssignmentError</span></span><a class="reference external" href="https://github.com/pandas-dev/pandas/blob/v2.2.2/pandas/errors/__init__.py#L455-L475"><span class="viewcode-link"><span class="pre">[source]</span></span></a>
</dt> <dd>
<p>Warning raised when trying to set using chained assignment.</p> <p>When the <code class="docutils literal notranslate"><span class="pre">mode.copy_on_write</span></code> option is enabled, chained assignment can never work. In such a situation, we are always setting into a temporary object that is the result of an indexing operation (getitem), which under Copy-on-Write always behaves as a copy. Thus, assigning through a chain can never update the original Series or DataFrame.</p> <p>For more information on view vs. copy, see <a class="reference internal" href="../../user_guide/indexing.html#indexing-view-versus-copy"><span class="std std-ref">the user guide</span></a>.</p> <p class="rubric">Examples</p> <div class="doctest highlight-default notranslate">
<div class="highlight"><pre data-language="python">&gt;&gt;&gt; pd.options.mode.copy_on_write = True
&gt;&gt;&gt; df = pd.DataFrame({'A': [1, 1, 1, 2, 2]}, columns=['A'])
&gt;&gt;&gt; df["A"][0:3] = 10 
... # ChainedAssignmentError: ...
&gt;&gt;&gt; pd.options.mode.copy_on_write = False
</pre></div> </div> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.ChainedAssignmentError.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.ChainedAssignmentError.html</a>
  </p>
</div>
