<h1>pandas.errors.InvalidVersion</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.InvalidVersion"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">InvalidVersion</span></span><a class="reference external" href="https://github.com/pandas-dev/pandas/blob/v2.2.2/pandas/util/version/__init__.py#L128-L137"><span class="viewcode-link"><span class="pre">[source]</span></span></a>
</dt> <dd>
<p>An invalid version was found, users should refer to PEP 440.</p> <p class="rubric">Examples</p> <div class="doctest highlight-default notranslate">
<div class="highlight"><pre data-language="python">&gt;&gt;&gt; pd.util.version.Version('1.')
Traceback (most recent call last):
InvalidVersion: Invalid version: '1.'
</pre></div> </div> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.InvalidVersion.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/2.2.2/reference/api/pandas.errors.InvalidVersion.html</a>
  </p>
</div>
