    <h1 id="firstHeading" class="firstHeading">std::runtime_error</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/stdexcept.html" title="cpp/header/stdexcept">&lt;stdexcept&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl"> <td class="t-dcl-nopad"> <pre data-language="cpp">class runtime_error;</pre>
</td> <td class="t-dcl-nopad"> </td> <td class="t-dcl-nopad"> </td> </tr>  </table> <p>Defines a type of object to be thrown as exception. It reports errors that are due to events beyond the scope of the program and can not be easily predicted.</p>
<p>Exceptions of type <code>std::runtime_error</code> are thrown by the following standard library components: <code><a href="../locale/locale/locale.html" title="cpp/locale/locale/locale">std::locale::locale</a></code> and <code><a href="../locale/locale/combine.html" title="cpp/locale/locale/combine">std::locale::combine</a></code>.</p>
<p>In addition, the following standard exception types are derived from <code>std::runtime_error</code>:</p>
<ul>
<li> <code><a href="range_error.html" title="cpp/error/range error">std::range_error</a></code> </li>
<li> <code><a href="overflow_error.html" title="cpp/error/overflow error">std::overflow_error</a></code> </li>
<li> <code><a href="underflow_error.html" title="cpp/error/underflow error">std::underflow_error</a></code> </li>
</ul> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <ul>
<li> <code><a href="../regex/regex_error.html" title="cpp/regex/regex error">std::regex_error</a></code> </li>
<li> <code><a href="system_error.html" title="cpp/error/system error">std::system_error</a></code> </li>
</ul> </td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx20">
<td> <ul>
<li> <code>std::chrono::ambiguous_local_time</code> </li>
<li> <code>std::chrono::nonexistent_local_time</code> </li>
<li> <code><a href="../utility/format/format_error.html" title="cpp/utility/format/format error">std::format_error</a></code> </li>
</ul> </td> <td><span class="t-mark-rev t-since-cxx20">(since C++20)</span></td>
</tr> </table> <div class="t-inheritance-diagram"> <div class="center"><div class="noresize">
<map name="ImageMap_1_1235887693"><area href="/w/cpp/error/exception.html" shape="rect" coords="5,4,107,36" alt="cpp/error/exception" title="cpp/error/exception"></map><img alt="std-runtime error-inheritance.svg" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+CjwhLS0gR2VuZXJhdGVkIGJ5IGdyYXBodml6IHZlcnNpb24gMi4yNi4zICgyMDEwMDEyNi4xNjAwKQogLS0+CjwhLS0gVGl0bGU6IGluaGVyaXRhbmNlIFBhZ2VzOiAxIC0tPgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHdpZHRoPSIyNDNweCIgaGVpZ2h0PSI0MHB4IiB2aWV3Qm94PSIwLjAwIDAuMDAgMjY5LjAwIDQ0LjAwIj4KPGcgaWQ9ImdyYXBoMSIgY2xhc3M9ImdyYXBoIiB0cmFuc2Zvcm09InJvdGF0ZSgwKSB0cmFuc2xhdGUoNCA0MCkiPgo8dGl0bGU+aW5oZXJpdGFuY2U8L3RpdGxlPgo8IS0tIGUxIC0tPgo8ZyBpZD0ibm9kZTEiIGNsYXNzPSJub2RlIj48dGl0bGU+ZTE8L3RpdGxlPgo8YT4KPHBvbHlnb24gZmlsbD0id2hpdGUiIHN0cm9rZT0iYmxhY2siIHBvaW50cz0iMTE1LC0zNiAxLC0zNiAxLC0xLjc3NjM2ZS0xNCAxMTUsLTMuNTUyNzFlLTE1IDExNSwtMzYiLz4KPHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iNTgiIHk9Ii0xNC40IiBmb250LWZhbWlseT0iRGVqYVZ1IFNhbnMsIHZlcmRhbmEsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTQuMDAiPmV4Y2VwdGlvbjwvdGV4dD4KPC9hPgo8L2c+CjwhLS0gZTIgLS0+CjxnIGlkPSJub2RlMiIgY2xhc3M9Im5vZGUiPjx0aXRsZT5lMjwvdGl0bGU+CjxhPgo8cG9seWdvbiBmaWxsPSJsaWdodGdyZXkiIHN0cm9rZT0iYmxhY2siIHBvaW50cz0iMjYwLC0zNiAxNDYsLTM2IDE0NiwtMS43NzYzNmUtMTQgMjYwLC0zLjU1MjcxZS0xNSAyNjAsLTM2Ii8+Cjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjIwMyIgeT0iLTE0LjQiIGZvbnQtZmFtaWx5PSJEZWphVnUgU2FucywgdmVyZGFuYSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNC4wMCI+cnVudGltZV9lcnJvcjwvdGV4dD4KPC9hPgo8L2c+CjwhLS0gZTImIzQ1OyZndDtlMSAtLT4KPGcgaWQ9ImVkZ2UyIiBjbGFzcz0iZWRnZSI+PHRpdGxlPmUyLSZndDtlMTwvdGl0bGU+CjxwYXRoIGZpbGw9Im5vbmUiIHN0cm9rZT0iYmxhY2siIGQ9Ik0xNDUuMjc2LC0xOEMxNDAuNTMyLC0xOCAxMzUuNywtMTggMTMwLjg2NywtMTgiLz4KPHBvbHlnb24gZmlsbD0ibm9uZSIgc3Ryb2tlPSJibGFjayIgcG9pbnRzPSIxMzAuNTI2LC0xMi43NTAxIDExNS41MjYsLTE4IDEzMC41MjYsLTIzLjI1MDEgMTMwLjUyNiwtMTIuNzUwMSIvPgo8L2c+CjwvZz4KPC9zdmc+Cg==" width="243" height="40" usemap="#ImageMap_1_1235887693">
</div></div> <div style="text-align:center;"> <p>Inheritance diagram</p>
</div> </div>  <h3 id="Member_functions"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><span class="t-lines"><span>(constructor)</span></span></div> </td> <td> constructs a new <code>runtime_error</code> object with the given message <br> <span class="t-mark">(public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><span class="t-lines"><span>operator=</span></span></div> </td> <td> replaces the <code>runtime_error</code> object <br> <span class="t-mark">(public member function)</span> </td>
</tr> </table> <div class="t-member"> <h2 id="std::runtime_error::runtime_error"> std::runtime_error::runtime_error</h2> <table class="t-dcl-begin"> <tr class="t-dcl"> <td> <pre data-language="cpp">runtime_error( const std::string&amp; what_arg );</pre>
</td> <td> (1) </td> <td class="t-dcl-nopad"> </td> </tr> <tr class="t-dcl"> <td> <pre data-language="cpp">runtime_error( const char* what_arg );</pre>
</td> <td> (2) </td> <td class="t-dcl-nopad"> </td> </tr>  <tr class="t-dcl-rev-aux"> <td></td> <td rowspan="3">(3)</td> <td></td> </tr> <tr class="t-dcl t-until-cxx11"> <td><pre data-language="cpp">runtime_error( const runtime_error&amp; other );</pre></td>  <td><span class="t-mark-rev t-until-cxx11">(until C++11)</span></td> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">runtime_error( const runtime_error&amp; other ) noexcept;</pre>
</td>  <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>   </table> <div class="t-li1">
<span class="t-li">1)</span> Constructs the exception object with <code>what_arg</code> as explanatory string. After construction, <code><a href="http://en.cppreference.com/w/cpp/string/byte/strcmp"><span class="kw1148">std::<span class="me2">strcmp</span></span></a><span class="br0">(</span>what<span class="br0">(</span><span class="br0">)</span>, what_arg.<span class="me1">c_str</span><span class="br0">(</span><span class="br0">)</span><span class="br0">)</span> <span class="sy1">==</span> <span class="nu0">0</span></code>.</div> <div class="t-li1">
<span class="t-li">2)</span> Constructs the exception object with <code>what_arg</code> as explanatory string. After construction, <code><a href="http://en.cppreference.com/w/cpp/string/byte/strcmp"><span class="kw1148">std::<span class="me2">strcmp</span></span></a><span class="br0">(</span>what<span class="br0">(</span><span class="br0">)</span>, what_arg<span class="br0">)</span> <span class="sy1">==</span> <span class="nu0">0</span></code>.</div> <div class="t-li1">
<span class="t-li">3)</span> Copy constructor. If <code>*this</code> and <code>other</code> both have dynamic type <code>std::runtime_error</code> then <code><a href="http://en.cppreference.com/w/cpp/string/byte/strcmp"><span class="kw1148">std::<span class="me2">strcmp</span></span></a><span class="br0">(</span>what<span class="br0">(</span><span class="br0">)</span>, other.<span class="me1">what</span><span class="br0">(</span><span class="br0">)</span><span class="br0">)</span> <span class="sy1">==</span> <span class="nu0">0</span></code>. <span class="t-rev-inl t-until-cxx11"><span>No exception can be thrown from the copy constructor.</span><span><span class="t-mark-rev t-until-cxx11">(until C++11)</span></span></span>
</div> <h3 id="Parameters"> Parameters</h3> <table class="t-par-begin"> <tr class="t-par"> <td> what_arg </td> <td> - </td> <td> explanatory string </td>
</tr> <tr class="t-par"> <td> other </td> <td> - </td> <td> another exception object to copy </td>
</tr>
</table> <h3 id="Exceptions"> Exceptions</h3> <div class="t-li1">
<span class="t-li">1,2)</span> May throw <code><a href="../memory/new/bad_alloc.html" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code>.</div> <h3 id="Notes"> Notes</h3> <p>Because copying <code>std::runtime_error</code> is not permitted to throw exceptions, this message is typically stored internally as a separately-allocated reference-counted string. This is also why there is no constructor taking <code>std::string&amp;&amp;</code>: it would have to copy the content anyway.</p>
<p>Before the resolution of <a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue254">LWG issue 254</a>, the non-copy constructor can only accept <code><a href="../string/basic_string.html" title="cpp/string/basic string">std::string</a></code>. It makes dynamic allocation mandatory in order to construct a <code><a href="../string/basic_string.html" title="cpp/string/basic string">std::string</a></code> object.</p>
<p>After the resolution of <a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue471">LWG issue 471</a>, a derived standard exception class must have a publicly accessible copy constructor. It can be implicitly defined as long as the explanatory strings obtained by <code>what()</code> are the same for the original object and the copied object.</p>
</div> <div class="t-member"> <h2 id="std::runtime_error::operator.3D"> std::runtime_error::operator=</h2> <table class="t-dcl-begin">   <tr class="t-dcl t-until-cxx11"> <td><pre data-language="cpp">runtime_error&amp; operator=( const runtime_error&amp; other );</pre></td> <td class="t-dcl-nopad"> </td> <td><span class="t-mark-rev t-until-cxx11">(until C++11)</span></td> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">runtime_error&amp; operator=( const runtime_error&amp; other ) noexcept;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>   </table> <p>Assigns the contents with those of <code>other</code>. If <code>*this</code> and <code>other</code> both have dynamic type <code>std::runtime_error</code> then <code><a href="http://en.cppreference.com/w/cpp/string/byte/strcmp"><span class="kw1148">std::<span class="me2">strcmp</span></span></a><span class="br0">(</span>what<span class="br0">(</span><span class="br0">)</span>, other.<span class="me1">what</span><span class="br0">(</span><span class="br0">)</span><span class="br0">)</span> <span class="sy1">==</span> <span class="nu0">0</span></code> after assignment. <span class="t-rev-inl t-until-cxx11"><span>No exception can be thrown from the copy assignment operator.</span><span><span class="t-mark-rev t-until-cxx11">(until C++11)</span></span></span></p>
<h3 id="Parameters_2"> Parameters</h3> <table class="t-par-begin"> <tr class="t-par"> <td> other </td> <td> - </td> <td> another exception object to assign with </td>
</tr>
</table> <h3 id="Return_value"> Return value</h3> <p><code>*this</code></p>
<h3 id="Notes_2"> Notes</h3> <p>After the resolution of <a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue471">LWG issue 471</a>, a derived standard exception class must have a publicly accessible copy assignment operator. It can be implicitly defined as long as the explanatory strings obtained by <code>what()</code> are the same for the original object and the copied object.</p>
</div> <div class="t-inherited"> <h2 id="Inherited_from_std::exception"> Inherited from <a href="exception.html" title="cpp/error/exception">std::exception</a>
</h2> <h3 id="Member_functions_2"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception/~exception.html" title="cpp/error/exception/~exception"> <span class="t-lines"><span>(destructor)</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> destroys the exception object <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="exception/what.html" title="cpp/error/exception/what"> <span class="t-lines"><span>what</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> returns an explanatory string <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span>  </td>
</tr> </table> </div> <h3 id="Defect_reports"> Defect reports</h3> <p>The following behavior-changing defect reports were applied retroactively to previously published C++ standards.</p>
<table class="dsctable"> <tr> <th>DR </th> <th>Applied to </th> <th>Behavior as published </th> <th>Correct behavior </th>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue254">LWG 254</a> </td> <td>C++98 </td> <td>the constructor accepting <code>const char*</code> was missing </td> <td>added </td>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue471">LWG 471</a> </td> <td>C++98 </td> <td>the explanatory strings of <code>std::runtime_error</code>'s<br>copies were implementation-defined </td> <td>they are the same as that of the<br>original <code>std::runtime_error</code> object </td>
</tr>
</table>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/runtime_error" class="_attribution-link">https://en.cppreference.com/w/cpp/error/runtime_error</a>
  </p>
</div>
